=== MaksPozdeev/LabBuildModules/xml_json_implementation/src/main/resources/xml/products.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subcategory" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="product" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="manufacturer" type="xs:string"/>
                                                    <xs:element name="model">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[a-zA-Z]{2}\d{3}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="dateOfManufacture">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string"> <!-- (DD-MM-YYYY)-->
                                                                <xs:pattern
                                                                        value="(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-(19|20)\d\d"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="color"> <!-- [a-zA-Z]{3,} -->
                                                        <xs:simpleType>
                                                            <xs:restriction>
                                                                <xs:pattern value="[a-zA-Z]{3,}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="price" type="xs:float" default="0.0"/>
                                                    <xs:element name="amount" type="xs:integer" default="0"/>

                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nameSubcategory" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nameCategory" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MaksPozdeev/LabBuildModules/xml_json_implementation/target/classes/xml/products.xml
<?xml version="1.0" encoding="UTF-8" ?>
<products
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="products.xsd">

    <category nameCategory="Audio equipment">
        <subcategory nameSubcategory="mp3 players">
            <product>
                <manufacturer>Ritmux</manufacturer>
                <model>mp001</model>                    <!-- AA999(two letters and three numbers).-->
                <dateOfManufacture>12-01-2018</dateOfManufacture> <!-- (DD-MM-YYYY).-->
                <color>Red</color>
                <price>19.99</price>
                <amount>7</amount>
            </product>

            <product>
                <manufacturer>SomY</manufacturer>
                <model>mp002</model>
                <dateOfManufacture>12-11-2018</dateOfManufacture>
                <color>Blue</color>
                <price>29.99</price>
                <amount>13</amount>
            </product>

            <product>
                <manufacturer>Dixp</manufacturer>
                <model>mp003</model>
                <dateOfManufacture>04-07-2018</dateOfManufacture>
                <color>Black</color>
                <price>9.99</price>
                <amount>15</amount>
            </product>

        </subcategory>

        <subcategory nameSubcategory="headphones">

            <product>
                <manufacturer>A3Teh</manufacturer>
                <model>ph001</model>
                <dateOfManufacture>22-01-2018</dateOfManufacture>
                <color>White</color>
                <price>29.99</price>
                <amount>7</amount>
            </product>

            <product>
                <manufacturer>BurnLine</manufacturer>
                <model>ph002</model>
                <dateOfManufacture>13-11-2019</dateOfManufacture>
                <color>Red</color>
                <price>24.49</price>
                <amount>8</amount>
            </product>
        </subcategory>

        <subcategory nameSubcategory="hi-fi speakers">
            <product>
                <manufacturer>Somy</manufacturer>
                <model>as001</model>
                <dateOfManufacture>22-11-2017</dateOfManufacture>
                <color>Brown</color>
                <price>59.99</price>
                <amount>4</amount>
            </product>

            <product>
                <manufacturer>Imaha</manufacturer>
                <model>as002</model>
                <dateOfManufacture>13-09-2019</dateOfManufacture>
                <color>Black</color>
                <price>79.99</price>
                <amount>3</amount>
            </product>
        </subcategory>
    </category>

    <category nameCategory="Video equipment">
        <subcategory nameSubcategory="TV set">
            <product>
                <manufacturer>Libis</manufacturer>
                <model>tv001</model>
                <dateOfManufacture>15-10-2016</dateOfManufacture>
                <color>Black</color>
                <price>31.99</price>
                <amount>3</amount>
            </product>

            <product>
                <manufacturer>Lizha</manufacturer>
                <model>tv002</model>
                <dateOfManufacture>21-11-2017</dateOfManufacture>
                <color>Black</color>
                <price>29.99</price>
                <amount>3</amount>
            </product>
        </subcategory>

        <subcategory nameSubcategory="Projectors">
            <product>
                <manufacturer>BanK</manufacturer>
                <model>pr001</model>
                <dateOfManufacture>27-07-2018</dateOfManufacture>
                <color>Blue</color>
                <price>57.99</price>
                <amount>4</amount>
            </product>

            <product>
                <manufacturer>RickoM</manufacturer>
                <model>pr002</model>
                <dateOfManufacture>12-03-2017</dateOfManufacture>
                <color>Green</color>
                <price>49.99</price>
                <amount>3</amount>
            </product>
        </subcategory>

        <subcategory nameSubcategory="blu ray">
            <product>
                <manufacturer>Dext</manufacturer>
                <model>br001</model>
                <dateOfManufacture>26-04-2027</dateOfManufacture>
                <color>Grey</color>
                <price>17.99</price>
                <amount>8</amount>
            </product>
        </subcategory>
    </category>

</products>

=== MaksPozdeev/LabBuildModules/xml_json_implementation/target/classes/xml/products_qa.xml
<?xml version="1.0" encoding="UTF-8" ?>
<products
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="products.xsd">

    <category nameCategory="Satellite systems">
        <subcategory nameSubcategory="receivers">
            <product>
                <manufacturer>Giniral Satellite</manufacturer>
                <model>ss001</model>                    <!-- AA999(two letters and three numbers).-->
                <dateOfManufacture>22-07-1999</dateOfManufacture> <!-- (DD-MM-YYYY).-->
                <color>Black</color>
                <price>14.99</price>
                <amount>7</amount>
            </product>

            <product>
                <manufacturer>SomY</manufacturer>
                <model>ss002</model>
                <dateOfManufacture>07-01-2018</dateOfManufacture>
                <color>Black</color>
                <price>34.33</price>
                <amount>13</amount>
            </product>
        </subcategory>

        <subcategory nameSubcategory="headphones TV">

            <product>
                <manufacturer>Sound3D</manufacturer>
                <model>ht001</model>
                <dateOfManufacture>22-01-2018</dateOfManufacture>
                <color>Black</color>
                <price>39.12</price>
                <amount>7</amount>
            </product>

            <product>
                <manufacturer>BurnLine</manufacturer>
                <model>ht002</model>
                <dateOfManufacture>13-11-2019</dateOfManufacture>
                <color>Red</color>
                <price>24.49</price>
                <amount>8</amount>
            </product>
        </subcategory>

        <subcategory nameSubcategory="hi-fi satelite">
            <product>
                <manufacturer>Somy</manufacturer>
                <model>as001</model>
                <dateOfManufacture>22-11-2017</dateOfManufacture>
                <color>Brown</color>
                <price>59.99</price>
                <amount>4</amount>
            </product>

            <product>
                <manufacturer>Irwa</manufacturer>
                <model>as002</model>
                <dateOfManufacture>13-09-2019</dateOfManufacture>
                <color>White</color>
                <price>79.99</price>
                <amount>3</amount>
            </product>
        </subcategory>
    </category>
</products>
